# Generated by Django 4.0.5 on 2022-06-11 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='datos_empresas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_empresa', models.CharField(max_length=120)),
                ('completed', models.BooleanField(default=False)),
                ('direccion', models.CharField(max_length=150)),
                ('nit', models.IntegerField()),
                ('telefono', models.CharField(max_length=20)),
            ],
        ),
    ]
