# Generated by Django 4.0.5 on 2022-06-11 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datos_empresas',
            name='completed',
        ),
    ]
